name: Build and Deploy

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

    workflow_dispatch:

jobs:
    test:
        name: Run integrated test units and linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python 
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Setup env and install dependencies
              run: |
                python -m venv env
                source env/bin/activate
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
                python -m pip list

            # - name: Run integrated test unit 
            #   run: |
            #     source env/bin/activate
            #     python -m pytest  

            - name: Run linter 
              run: |
                source env/bin/activate
                python -m pylint --fail-under=7 $(git ls-files '*.py')
